### ISSUE TITLE
target_collateral_ratio for extensions

### ISSUE THREAD

**Issue by kuruharbi** [bitshares/python-bitshares#158]
We can use target collateral ratio in UI
![image](https://user-images.githubusercontent.com/26321769/47617394-d9b2d600-dad7-11e8-99e8-c2e315f396a5.png)

but in python-bitshares API I can not use it
please check https://github.com/bitshares/python-bitshares/blob/master/bitsharesbase/operations.py

For example

class Call_order_update(GrapheneObject):
    def __init__(self, *args, **kwargs):
        if isArgsThisClass(self, args):
                self.data = args[0].data
        else:
            if len(args) == 1 and len(kwargs) == 0:
                kwargs = args[0]
            super().__init__(OrderedDict([
                ('fee', Asset(kwargs["fee"])),
                ('funding_account', ObjectId(kwargs["funding_account"], "account")),
                ('delta_collateral', Asset(kwargs["delta_collateral"])),
                ('delta_debt', Asset(kwargs["delta_debt"])),
                ('extensions', Set([])),
            ]))

extensions is always equal to Set([]) so that we can not define parameter for target_collateral_ratio

    op = operations.Call_order_update(**{
        'fee': {'amount': 0, 'asset_id': '1.3.0'},
        'delta_debt': {
            'amount': 0,
            'asset_id': asset["id"]},
        'delta_collateral': {
            'amount': int(float(free_bts - 10) * 10 ** collateral_asset["precision"]),
            'asset_id': collateral_asset["id"]},
        'funding_account': account["id"],
        'extensions': {'target_collateral_ratio':1750}
    })
bitshares.finalizeOp(op, account["name"], "active")

**Comment by kuruharbi** [comment]
I learned it is solved in developer branch

**Comment by xeroc** [comment]
what is still missing is the inclusion of that feature in the pybitshares API. So far, only the serialization is available.

**Comment by xeroc** [comment]
Ok, serialization works now, and the existing calls in `dex.py` now have an interface to the extension.

**Comment by xeroc** [comment]
this appears to be working as intended now. If anyone runs into problems, please open up a new issue

**Comment by wwwang89** [comment]
hello，everyone，when I set TCR in “broadcast_transaction_with_callback” method，
my Operation data like bellow：
{
	fee = {
		asset_id = 1.3 .0;
		amount = 0;
	};
	extensions = {
		target_collateral_ratio = 1760;
	};
	funding_account = 1.2 .1097304;
	delta_debt = {
		asset_id = 1.3 .113;
		amount = 0;
	};
	delta_collateral = {
		asset_id = 1.3 .0;
		amount = 1;
	};
}

but error occurred，error:missing required active authority: Missing Active Authority ...
I think the signatures is wrong，because  when I not set  target_collateral_ratio，the data below
{
	fee = {
		asset_id = 1.3 .0;
		amount = 0;
	};
	funding_account = 1.2 .1097304;
	delta_debt = {
		asset_id = 1.3 .113;
		amount = 0;
	};
	delta_collateral = {
		asset_id = 1.3 .0;
		amount = 1;
	};
}

It succeed ！

So I am confused how the property "target_collateral_ratio" signs on the line chain ？

anyone help ？

thanks ！！

**Comment by xeroc** [comment]
in `bitshares.dex.Dex()` there is a method called

```python
    def adjust_collateral_ratio(self, symbol, new_collateral_ratio, account=None, target_collateral_ratio=None):
```
Please try that.
